services:
  blockchain:
    image: hyperledger/besu:latest
    container_name: besu-node
    ports:
      - "8545:8545"   # JSON-RPC HTTP
      - "8546:8546"   # WebSocket (opcional)
      - "30303:30303" # P2P
    
    command: >
      --network=dev
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=*
      --rpc-http-api=ETH,NET,WEB3,QBFT,ADMIN,PERM
      --host-allowlist=*
    # --config-file=/config/config.toml
    volumes:
      - besu-data:/var/lib/besu
      - ./config:/config:ro
volumes:
  besu-data: